### ISSUE TITLE
Error During Installation

### ISSUE THREAD

**Issue by rebeltom** [futuretechlab/BravoPrinterEfficiencyTool#4] opened 2017-11-15 19:31 UTC
![image](https://user-images.githubusercontent.com/33700814/32855950-2baa6190-c9f8-11e7-9004-d4874e438044.png)

I ran the installer on my computer, everything was good up to the actual installation.  Received the error shown in the screenshot for Labels, ATags, SpecialLabels, Reports, and PawnTickets.  The Receipts printer installed just fine.

**Comment by futuretechlab** [comment] 2017-11-15 20:24
I got this error before when I was using the older version of the Zebra inf file with the edited names. We added a list of supported printers to the installation procedure recently. Could you give me some more details about what drivers you had selected for these specific printers?

**Comment by rebeltom** [comment] 2017-11-15 20:26
I just grabbed the model from the dropdown list.  I didn't have to select drivers for the Zebra printers.

**Comment by rebeltom** [comment] 2017-11-15 20:27
For the PawnTickets and Reports, I used an INF that was successfully used on a different user's computer.

**Comment by futuretechlab** [comment] 2017-11-15 20:34
Yes... Sorry, Which models did you have selected for Labels, ATags, SpecialLabels? What INF did you use for the PawnTickets and Reports? When you selected this INF for the PawnTickets and Reports, what model did you select from the dropdown? Also how did you obtain the INF? INF files are dependent on their surrounding files for the resources they need to install the driver. Simply transferring just the INF is not enough.

**Comment by rebeltom** [comment] 2017-11-15 20:46
Ok,

So for the Labels and ATags, I selected the Zdesigner TLP 2824 Plus (ZPL) from the dropdown in the tool.  For SpecialLabels, I selected the Zdesigner GX420t.

For the PawnTickets and Reports, I selected the Other Manufacturer and the model was Brother DCP-L2520 DW series.

INF was BRPRM13A.  It came from the file sent to me from another tech that actually had success with it.  I cant attach the file because it is too large. I tried to compress it in a ZIP, but still too large.

I hope this helps.

Let me know if you have more questions.

Thanks!

Tom VanCott | Onboarding Coordinator
Bravo Store Systems | Buya Marketplace

Office: 888-407-6287 | Direct: 725-502-1873
Email: tom@buya.com
Facebook| LinkedIn



IMPORTANT: The information in this e-mail is the property of Bravo. This e-mail message is for the sole use of the intended recipient(s) to which it is addressed, and may contain information that is privileged, CONFIDENTIAL, and exempt from disclosure under applicable law. Any unauthorized review, use, disclosure, or distribution is prohibited. If you are not the intended recipient, please contact the sender immediately by reply e-mail and destroy all copies of the original message.

________________________________

**Comment by futuretechlab** [comment] 2017-11-16 20:49
Don't worry about attaching files here. We'll just have to keep an eye out for this bug. It sounds like the tech that provided the BRPRM13A INF may have sent it to you without the essential auxiliary files that the INF needs to install the drivers (at least that's my guess). I tested the installation yesterday on the Test Bed PC and everything went very well.

I'm updating the file path handling for INF parsing, and I hope that resolves the ZBRN.inf error.

**Comment by rebeltom** [comment] 2017-11-17 00:18
Update:
I got the same errors again with the new download I got today.

I recorded a video of the process. But I don't know what to do to give it to you. It's too large.

**Comment by rebeltom** [comment] 2017-11-29 18:28
@futuretechlab If you want you can call me directly for more info.  I don't have your number to call you. My work number is 725-502-1873.
I will do what I can to help improve the install tool.

**Comment by futuretechlab** [comment] 2017-12-06 15:49
I'm releasing a new version which addresses this and other issues with adding drivers from the INF. This error was caused by over-specific checking of the output of pnputil. I've updated the error messages and the packaged driver files and I will be releasing v1.2.2 shortly.

**Closed by futuretechlab** 2017-12-06 15:49 UTC
